CREATE DATABASE DB_NAME;
CREATE USER DB_USER WITH PASSWORD 'DB_PWD';
GRANT ALL PRIVILEGES ON DATABASE DB_NAME TO DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO DB_USER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to DB_USER;

CREATE TABLE user_table(
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE
);
